### ISSUE TITLE
Peer Dependencies 

### ISSUE THREAD

**Issue by stooboo** [cezary/react-diff#1]
Hi 

the peer dependencies are declared as 

```
"peerDependencies": {
    "react": "^0.12.0 < 0.14.0"
  },
```

this doesn't work for me with react@0.13.3 

I changed the dependencies locally to be

```
"peerDependencies": {
    "react": ">0.12.0 <0.14.0"
  },
```

and it works ;-)

cheers
Stu

**Comment by cezary** [comment]
Thanks for letting me know, fixed!
